version: 2.1

parameters:
  developername:
    type: string
    default: "developer1"
  imagetag:
    type: string
    default: "latest"

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:1.4.0
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN

jobs:
  setup:
    docker:
      - image: python:3.9
    working_directory: ~/repo/multi-service
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Install Python dependencies
          command: pip install pyhcl
      - run:
          name: Modify locals.tf
          command: python script.py developername=<< pipeline.parameters.developername >> imagetag=<< pipeline.parameters.imagetag >>
      - run:
          name: print locals.tf
          command: cat locals.tf     
      - persist_to_workspace:
          root: ~/repo/multi-service
          paths: 
            - locals.tf

  plan-apply:
    executor: terraform-executor
    working_directory: ~/repo/multi-service
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo/multi-service

      - run:
          name: Check AWS Environment Variables
          command: |
            export AWS_DEFAULT_REGION="us-west-2"
            echo "Checking if AWS_ACCESS_KEY_ID is set: ${AWS_ACCESS_KEY_ID:+SET}"
            echo "Checking if AWS_SECRET_ACCESS_KEY is set: ${AWS_SECRET_ACCESS_KEY:+SET}"
            echo "Checking if AWS_DEFAULT_REGION is set: ${AWS_DEFAULT_REGION}"
            echo "Checking if AWS_SESSION_TOKEN is set: ${AWS_SESSION_TOKEN+SET}"

      - run:
          name: Print all environment variables
          command: printenv 
              
      - run:
          name: Initialize Terraform
          command: terraform init -backend-config="region=$AWS_DEFAULT_REGION" -backend-config="access_key=$AWS_ACCESS_KEY_ID" -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY"
      - run:
          name: Terraform Plan
          command: terraform plan

workflows:
  version: 2
  build:
    jobs:
      - setup
      - plan-apply:
          requires:
            - setup