version: '2.1'

orbs:
  terraform: circleci/terraform@3.1

jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - run:
          name: Check Directory Before Checkout
          command: |
            ls -la && pwd
      - checkout
      - run:
          name: Check Directory After Checkout
          command: |
            ls -1a && pwd
      - run:
          name: Manually Install Terraform
          command: |
            wget "https://releases.hashicorp.com/terraform/1.4.0/terraform_1.4.0_linux_amd64.zip" -O terraform_1.4.0_linux_amd64.zip
            unzip -o terraform_1.4.0_linux_amd64.zip
            mv terraform /usr/local/bin/
      
      - run:
          name: Set Environment Variables
          command: |
            echo 'export AWS_ACCESS_KEY_ID=AKIAZ3LRTZ263UQWAVMK' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=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' >> $BASH_ENV
            echo 'export AWS_DEFAULT_REGION=us-west-2' >> $BASH_ENV 
            cd ./multi-service && terraform init
      
      - terraform/init:
          path: ./multi-service

      - terraform/validate:
          path: ./multi-service 

      - terraform/fmt:
          path: ./multi-service 

      - terraform/plan:
          path: ./multi-service 
    working_directory: ~/repo

workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle:
          context:
             - terraform
