version: 2.1

parameters:
  developername:
    type: string
    default: "developer1"
  imagetag:
    type: string
    default: "latest"

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:1.4.0
    environment:
      AWS_ACCESS_KEY_ID: ${ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${DEFAULT_REGION}

jobs:
  setup:
    docker:
      - image: python:3.9
    working_directory: ~/repo/multi-service
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Install Python dependencies
          command: pip install pyhcl
      - run:
          name: Modify locals.tf
          command: python script.py developername=<< pipeline.parameters.developername >> imagetag=<< pipeline.parameters.imagetag >>
      - run:
          name: Cat locals.tf
          command: cat locals.tf  
      - run:
          name: Create Backend Configuration File
          command: |
            echo "region = \"us-west-2\"" > backend-config.tfvars
      - persist_to_workspace:
          root: ~/repo/multi-service
          paths: 
            - locals.tf
            - backend-config.tfvars

  plan-apply:
    executor: terraform-executor
    working_directory: ~/repo/multi-service
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo/multi-service
      - run:
          name: Initialize Terraform
          command: terraform init -backend-config=backend-config.tfvars -backend-config="access_key=${ACCESS_KEY_ID}" -backend-config="secret_key=${SECRET_ACCESS_KEY}"
      - run:
          name: Terraform Plan
          command: terraform plan -var-file=backend-config.tfvars -var="my_access_key=${ACCESS_KEY_ID}" -var="my_secret_key=${SECRET_ACCESS_KEY}"

workflows:
  version: 2
  build:
    jobs:
      - setup
      - plan-apply:
          requires:
            - setup
