version: 2.1

parameters:
  developername:
    type: string
    default: "developer1"
  imagetag:
    type: string
    default: "latest"

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:0.14.5
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

jobs:
  setup:
    docker:
      - image: python:3.9
    working_directory: ~/repo/multi-service
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Install Python dependencies
          command: pip install pyhcl
      - run:
          name: Modify locals.tf
          command: python script.py developername=<< pipeline.parameters.developername >> imagetag=<< pipeline.parameters.imagetag >>
      - run:
          name: print locals.tf
          command: cat locals.tf     
      - persist_to_workspace:
          root: ~/repo/multi-service
          paths: 
            - locals.tf

  plan-apply:
    executor: terraform-executor
    working_directory: ~/repo/multi-service
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo/multi-service
      - run:
          name: Initialize Terraform
          command: terraform init
      - run:
          name: Terraform Plan
          command: terraform plan
          
workflows:
  version: 2
  build:
    jobs:
      - setup
      - plan-apply:
          requires:
            - setup