version: '2.1'

orbs:
  terraform: circleci/terraform@3.1

jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout:
          path: ~/repo
      - terraform/fmt:
          path: ~/repo/multi-service
      - terraform/validate:
          path: ~/repo/multi-service
      - terraform/init:
          backend: true
          path: ~/repo/multi-service
      - terraform/plan:
          path: ~/repo/multi-service
    working_directory: ~/repo/multi-service

workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle:
          context:
             - terraform
