version: '2.1'

orbs:
  terraform: circleci/terraform@3.1

jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - run:
          name: Check Directory Before Checkout
          command: |
            ls -la && pwd
      - checkout
      - run:
          name: Check Directory After Checkout
          command: |
            ls -1a && pwd
      - run:
          name: Manually Install Terraform
          command: |
            wget "https://releases.hashicorp.com/terraform/1.4.0/terraform_1.4.0_linux_amd64.zip" -O terraform_1.4.0_linux_amd64.zip
            unzip -o terraform_1.4.0_linux_amd64.zip
            mv terraform /usr/local/bin/
      - terraform/init:
          name: init
          path: ./multi-service

      - terraform/validate:
          name: validate
          path: ./multi-service 

      - terraform/fmt:
          name: fmt
          path: ./multi-service 

      - terraform/plan:
          name: plan
          path: ./multi-service 
    working_directory: ~/repo

workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle:
          context:
             - terraform
