version: '2.1'

orbs:
  terraform: circleci/terraform@3.1

jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ~/multi-service
      - terraform/validate:
          path: ~/multi-service
      - terraform/init:
          backend: true
          path: ~/multi-service
      - terraform/plan:
          path: ~/multi-service
    working_directory: ~/multi-service

workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle:
          context:
             - terraform
