version: '2.1'

orbs:
  terraform: circleci/terraform@3.1

jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - run:
          name: Check Directory Before Checkout
          command: |
            ls -la && pwd
      - checkout
      - run:
          name: Check Directory After Checkout
          command: |
            ls -1a && pwd
      - terraform/install:
          terraform_version: 1.4.0
      - terraform/validate:
          path: ./multi-service 
      - terraform/fmt:
          path: ./multi-service 
      - terraform/plan:
          path: ./multi-service 
    working_directory: ~/repo

workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle:
          context:
             - terraform