version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.6

parameters:
  developername:
    type: string
    default: "developer1"
  imagetag:
    type: string
    default: "latest"

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:1.4.0
    environment:
      AWS_ACCESS_KEY_ID: ${ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${DEFAULT_REGION}

jobs:
  setup:
    docker:
      - image: python:3.9
    working_directory: ~/repo/multi-service
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Install Python dependencies
          command: pip install pyhcl
      - run:
          name: Modify locals.tf
          command: python script.py developername=<< pipeline.parameters.developername >> imagetag=<< pipeline.parameters.imagetag >>
      - run:
          name: print locals.tf
          command: cat locals.tf     
      - persist_to_workspace:
          root: ~/repo/multi-service
          paths: 
            - locals.tf

  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME    
      - run:
          name: "whoami"
          command: aws sts get-caller-identity          

  plan-apply:
    executor: terraform-executor
    working_directory: ~/repo/multi-service
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo/multi-service

      - run:
          name: Check AWS Environment Variables
          command: |

            echo "Checking ${ACCESS_KEY_ID}"
            echo "Checking  ${SECRET_ACCESS_KEY:+SET}"
            echo "Checking ${DEFAULT_REGION}"

      - run:
          name: "Setup custom environment variables"
          command: |
            echo 'export AWS_ACCESS_KEY_ID=${ACCESS_KEY_ID}' >> "$BASH_ENV"  
            printenv
            echo $AWS_ACCESS_KEY_ID

      - run:
          name: Print all environment variables
          command: printenv 

      
              # check
      - run:
          name: Initialize Terraform
          command: |
            echo "access_key = \"$ACCESS_KEY_ID\"" > backend-config.tfvars
            echo "secret_key = \"$SECRET_ACCESS_KEY\"" >> backend-config.tfvars
            echo "region = \"us-west-2\"" >> backend-config.tfvars
            terraform init -backend-config="region=$DEFAULT_REGION"
            terraform plan -var-file=backend-config.tfvars

      - run:
          name: Terraform Plan
          command: terraform plan

workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli-cred-setup:
          context: aws
  build:
    jobs:
      - setup
      - plan-apply:
          requires:
            - setup