version: '2.1'

orbs:
  terraform: circleci/terraform@3.1

jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - run:
          name: Check AWS Environment Variables
          command: |
            ls -la && pwd
      
      - checkout
      - run:
          name: Check AWS Environment Variables
          command: |
            ls -1a && pwd && tree
      - terraform/fmt
      - terraform/validate
        
      - terraform/init:
          backend: true
         
      - terraform/plan
       
    working_directory: ~/repo/multi-service

workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle:
          context:
             - terraform
