version: '2.1'

orbs:
  terraform: circleci/terraform@3.1

jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - run:
          name: Check AWS Environment Variables
          command: |
            ls -la && pwd
      - checkout
      - run:
          name: Check AWS Environment Variables
          command: |
            ls -1a && pwd

      - terraform/validate:
          path: ./multi-service 
      - terraform/validate:
          path: ./multi-service    
      - terraform/fmt:
          path: ./multi-service 
      - terraform/plan:
          path: ./multi-service 
       
    working_directory: ~/repo

workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle:
          context:
             - terraform
